set1 = {20,2,"Ajay","Python","Nepal"}
print(set1)
print()
print(len(set1))
print()
print(type(set1))
print()
print("Ajay" in set1)
print()
set1.add("Dangoriya")
print(set1)
print()
set1.remove("Dangoriya")
print(set1)
print()
set2=set(set1)
set2.clear()
print(set2)
print()
set3=set(set1)
set4=("Btech",11222780,"G section")
set3.update(set4)
print(set3)
print()
set5=set3.intersection(set1)
print(set5)
print()
print(set3.pop())
