#Uses of String Operators

a="@Ajay dagoriya tharu    "
print() 
print(a)
print("Lenght of String :",len(a))
print() 
print(a)
print("Minumum word of String :", min(a))
print() 
print(a)
print("Maximum word of String :",max(a))
print() 
print(a)
print("UpperCase of String :",a.upper())
print() 
print(a)
print("LowerCase of String :",a.lower())
print() 
print(a)
print("is the string in UpperCase :",a.isupper())
print() 
print(a)
print("is the string in LowerCase :",a.islower())
print() 
print(a)
print("String Starts form g : ",a.startswith('g'))
print() 
print(a)
print("String End with a:",a.endswith('a'))
print() 
print(a)
print("Find o in String :",a.find('o'))
print() 
print(a)
print("Replace g with Z on string :",a.replace('g','Z'))
print() 
print(a)
print("Split form d :",a.split('d'))
print() 
print(a)
print("To strip the string :",a.strip())
print() 
print(a)
print("Partation form i",a.partition('i'))
print() 
print(a)
print("check digits in string:",a.isdigit())
print() 
print(a)
print("Uppercase the 1st leter of word :",a.title())
print() 
print(a)
print("check the 1st leter of word ia capital or not:",a.istitle())
print() 
print(a)
print("To capitalize the string :",a.capitalize())
print() 
print(a)
print("To check the string is start with alphabet or not :",a.isalpha())
print() 
print(a)
print("To check the string is start with number or not :",a.isalnum())
print() 
print(a)
print("To lstrip the string :",a.lstrip())
print() 
print(a)
print("To rstrip the string :",a.rstrip())