a=("Ajay",20,30,40,'SandY')
print()
print(a)
print("Uses of + operator :",(a+a))
print()
print(a)
print("Uses of * operator :",(a*3))
print()
print(a)
print("Uses of in operator :",("Ajay" in a))
